server:
  port: 8761
  servlet:
    context-path: /

spring:
  profiles: slave1
  application:
    name: slave1
  security:
    user:
      name: dev
      password: dev
  devtools:
    restart:
      enabled: false
eureka:
  instance:
    hostname: slave1
    metadataMap:
      user: dev
      password: dev
      configPath: /config
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 3
    prefer-ip-address: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://slave2:8762/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
---
server:
  port: 8762
  servlet:
    context-path: /

spring:
  profiles: slave2
  application:
    name: slave2
  security:
    user:
      name: dev
      password: dev
  devtools:
    restart:
      enabled: false
eureka:
  instance:
    hostname: slave2
    metadataMap:
      user: dev
      password: dev
      configPath: /config
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 3
    prefer-ip-address: false
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://slave1:8761/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000

