server:
  port: 8761
  servlet:
    context-path: /eureka

spring:
  application:
    name: eureka
  security:
    user:
      name: dev
      password: dev
eureka:
  instance:
    hostname: 127.0.0.1
    metadataMap:
      user: dev
      password: dev
      configPath: /config
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 3
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000

